batch_type: numel
batch_bins: 3200000
accum_grad: 1
max_epoch: 60
patience: none
# The initialization method for model parameters
init: xavier_uniform
best_model_criterion:
-   - valid
    - loss
    - min
keep_nbest_models: 10

init_param: [
    "../../librispeech/ssl1_local/exp/hubert_iter0_train_ssl_torchaudiohubert_base_960h_pretrain_it1_raw/valid.loss.best.pth:encoder:encoder"
]

input_size: 1
encoder: torchaudiohubert
encoder_conf:
    encoder_projection_dropout: 0.0
    encoder_attention_dropout: 0.0
    encoder_ff_interm_dropout: 0.1
    encoder_dropout: 0.0
    encoder_layer_drop: 0.0
    finetuning: true
    freeze_encoder_updates: 4000

model_conf:
    ctc_weight: 1.0
    lsm_weight: 0.1
    length_normalized_loss: false

optim: adam
optim_conf:
    lr: 0.00005
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 6000

unused_parameters: true

frontend: null

normalize: null

specaug: null
